#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile.ssl for crypto/cversion.c */
  #define CFLAGS "ccppc -DOPENSSL_SYSNAME_VXWORKS -DOPENSSL_NO_KRB5 -DOPENSSL_NO_HW -DOPENSSL_NO_ASM -DOPENSSL_NO_MDC5 -DOPENSSL_NO_IDEA -DOPENSSL_NO_RC5 -mcpu=603 -mstrict-align -ansi -O2 -fstrength-reduce -fno-builtin -Wall -DCPU=PPC603 -DTOOL_FAMILY=gnu -DTOOL=gnu -DNO_STRINGS_H -I/folk/calvinw/Tornado/ppc/2.2.1-Stampede/target/h "
  #define PLATFORM "vxworks-ppc603"
  #define DATE "Wed Mar 24 16:37:19 MST 2004"
#endif
